name: Create-File
on: push
jobs:
  create-file:
    name: Create and Upload File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run main.py file
        run: python main.py
      - name: Archive sample artifacts
        uses: actions/upload-artifact@v2
        with:
          name: all txt file
          path: sample.txt
